robot_sim:
  laser_config:
    angle_min: -1.57
    angle_max: 1.57
    angle_increment: 0.01
    range_min: 0.0
    range_max: 3.0
    time_increment: 0.001
  noise:
    # odom_variance: 0.003
    odom_variance: 0.0
    laser_variance: 0.0002
  init_state:
    # meters
    x: 1.0
    y: 1.0
    # radians
    theta: 0.0
    # m/s
    v: 0.0
    # rad/s
    w: 0.0