FROM create2-base:latest

ENV WS=beertender_robot

RUN mkdir -p /${WS}/src /${WS}/install 
COPY src /${WS}/src/.
RUN rm -rf ${WS}/src/simulation

RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections

RUN . /opt/ros/melodic/setup.sh && rosdep install --from-path /${WS} --ignore-src -y

RUN cd ${WS} && . /opt/ros/melodic/setup.sh && catkin config --install --extend ../catkin_isolated_ws/install_isolated && catkin build
