FROM sdk-base:latest

ENV WS=beertender_robot

RUN mkdir -p /${WS}/src /${WS}/install 
COPY src /${WS}/src/.

RUN . /opt/ros/melodic/setup.sh && rosdep install --from-path /${WS} --ignore-src -y

# RUN cd ${WS} && . /opt/ros/melodic/setup.sh && catkin config --install && catkin build
