# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      ROS_DISTRO: noetic
    steps:
      - uses: venkisagunner93/ros_github_actions
      - name: catkin_make
        run: |
          ls
          source /opt/ros/$ROS_DISTRO/setup.bash
          cd /beertender_robot
          catkin_make
