# This is a basic workflow to help you get started with Actions
name: CI
on: [push]
jobs:    
  build-sdk:
    runs-on: self-hosted
    container: docker://venkisagunner93/sdk-base:latest
    steps:
      - uses: AutoModality/action-clean@v1
      - uses: actions/checkout@v1          
      - name: Build package
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          mkdir install/ logs/ && source /opt/ros/melodic/setup.bash && catkin config --install
  clean-up-sdk:
    runs-on: self-hosted
    needs: build-sdk
    steps:
      - name: Clean working directory
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE && ls -la
          sudo rm -rf * && ls -la
#   build-robot:
#     runs-on: self-hosted
#     needs: clean-up-sdk
#     container: docker://venkisagunner93/create2-base:latest
#     steps:
#       - uses: AutoModality/action-clean@v1
#       - uses: actions/checkout@v1          
#       - name: Build package
#         shell: bash
#         run: |
#           cd $GITHUB_WORKSPACE && rm -rf src/simulation
#           source /opt/ros/melodic/setup.bash && rosdep init && rosdep update && rosdep install --from-path $GITHUB_WORKSPACE --ignore-src -y
#           mkdir install/ logs/ && source /opt/ros/melodic/setup.bash && catkin config --install && catkin build
#   clean-up-robot:
#     runs-on: self-hosted
#     needs: build-robot
#     steps:
#       - name: Clean working directory
#         shell: bash
#         run: |
#           cd $GITHUB_WORKSPACE
#           sudo rm -rf *
