# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      ROS_DISTRO: noetic
    steps:
      - uses: actions/checkout@v2
      - name: catkin_make
        run: |
          source /opt/ros/$ROS_DISTRO/setup.bash
          cd /beertender_robot
          catkin_make
